# Generated by Django 4.2.1 on 2023-06-07 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_services_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='icon',
            field=models.CharField(choices=[('bi-briefcase', 'briefcase'), ('bi-card-checklist', 'checklist'), ('bi-bar-chart', 'chart'), ('bi-binoculars', 'binoculars'), ('bi-brightness-high', 'brightness-high'), ('bi-calendar4-week', 'calendar4-week')], max_length=250),
        ),
    ]
