# Generated by Django 4.2.1 on 2023-06-07 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_services_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testi',
            name='img',
            field=models.CharField(choices=[('testimonials-1.jpg', 'image 1'), ('testimonials-2.jpg', 'image 2'), ('testimonials-3.jpg', 'image 3'), ('testimonials-4.jpg', 'image 4'), ('testimonials-5.jpg', 'image 5')], max_length=255),
        ),
    ]
