# Generated by Django 4.2.1 on 2023-06-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_cont'),
    ]

    operations = [
        migrations.CreateModel(
            name='Filtre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filtre', models.CharField(max_length=255)),
            ],
        ),
    ]
