# Generated by Django 4.2.1 on 2023-06-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_filtre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Porto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(choices=[('portfolio-1.jpg', 'image 1'), ('portfolio-2.jpg', 'image 2'), ('portfolio-3.jpg', 'image 3'), ('portfolio-4.jpg', 'image 4'), ('portfolio-5.jpg', 'image 5'), ('portfolio-6.jpg', 'image 6'), ('portfolio-7.jpg', 'image 7'), ('portfolio-8.jpg', 'image 8'), ('portfolio-9.jpg', 'image 9')], max_length=255)),
                ('filtre', models.CharField(max_length=255)),
            ],
        ),
    ]
